version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.0.4
  aws-ecs: circleci/aws-ecs@4.0
  aws-cli: circleci/aws-cli@4.1.3

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build_and_push_image:
          auth:
            - aws-cli/setup:
                #role_arn: arn:aws:iam::339712738994:role/aws-service-role/replication.ecr.amazonaws.com/AWSServiceRoleForECRReplication
          repo: ecr_repo_from_tf_lab
          tag: latest #${CIRCLE_SHA1}

      - aws-ecs/deploy_service_update:
          auth:
            - aws-cli/setup:
          requires:
            - aws-ecr/build_and_push_image # only run this job once aws-ecr/build-and-push-image has completed
          family: ReactCircleCITaskDefinition
          service_name: ReactServiceTest2
          cluster: TestClusterWithCircleCiImage2
          container_image_name_updates: container=container_image,tag=latest #${CIRCLE_SHA1}
