version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.0.4
  aws-ecs: circleci/aws-ecs@4.0
  aws-cli: circleci/aws-cli@4.0

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build_and_push_image:
          account_id: ${AWS_ACCOUNT_ID}
          auth:
            - aws-cli/setup:
                profile: michael
                role_arn: arn:aws:iam::339712738994:role/ecsTaskExecutionRole
          repo: "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/ecr_repo_from_tf_lab"
          tag: "${CIRCLE_SHA1}"
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build_and_push_image # only run this job once aws-ecr/build-and-push-image has completed
          family: "ReactTestTaskDefinition"
          cluster: "ReactTestCluster"
          container-image-name-updates: "container=container_image,tag=${CIRCLE_SHA1}"
