version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.0.4
  aws-ecs: circleci/aws-ecs@4.0

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build_and_push_image:
          repo: "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/ecr_repo_from_tf_lab"
          tag: "${CIRCLE_SHA1}"
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build_and_push_image # only run this job once aws-ecr/build-and-push-image has completed
          family: "ReactCircleCITaskDefinitio"
          cluster: "TestClusterWithCircleCiImage"
          container-image-name-updates: "container=image,tag=${CIRCLE_SHA1}"
