version: 2.1
jobs:
  deploy-react:
    docker:
      - image: circleci/node:18
    working_directory: ~/repo
    steps:
      - checkout
      # install dependencies
      - setup_remote_docker:
          version: 20.10.12
          docker_layer_caching: true
      # - run:
      #     name: Run npm
      #     command: |
      #       npm install
      # Install AWS CLI
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y awscli

      # Authenticate with AWS ECR
      - run:
          name: Configure AWS credentials
          command: aws configure set default.region $AWS_DEFAULT_REGION

      # Build Docker image
      - run:
          name: Build Docker image
          command: |
            docker build -t yourimage:latest .

      # Tag Docker image for ECR
      - run:
          name: Tag Docker image for ECR
          command: |
            docker tag yourimage:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/ecr_repo_from_tf_lab:latest

      # Push Docker image to ECR
      - run:
          name: Push Docker image to ECR
          command: |
            aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/ecr_repo_from_tf_lab:latest

workflows:
  version: 2
  job_deploy:
    jobs:
      - deploy-react
